defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

scheduler:
  decay_rate: 0.95
  decay_steps: 15000

training:
  rec_results_freq : 1000
  rec_constraint_freq: 10000
  max_steps : 2000000

batch_size:
  backBC: 6000
  frontBC: 600
  surfaceBC: 16500
  interior_support: 12500
  interior_bracket: 4500
